### PR TITLE
Update the table of contents for readme and migration files 

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-tracking bundle size difference from 2.0.10 to 791d0b876a0fa1385edb9456aaf7ff36865c2e88
js: 4.01kb increase (1.41kb/gzip)

**Comment by origamiserviceuser** [comment]
o-tracking bundle size difference from 2.0.10 to 45bd2981b6bfd9a2ee7cfdb1c39389e09ad0a822
js: 4.01kb increase (1.41kb/gzip)

**Comment by origamiserviceuser** [comment]
o-tracking bundle size difference from 2.0.10 to 2f1b46f760c3c45b9ea7e48d5a7ecc0c7c41e06b
js: 4.01kb increase (1.41kb/gzip)

**Comment by origamiserviceuser** [comment]
o-tracking bundle size difference from 2.0.10 to caa72dc5c1bd5196a1d07cef1e79e80ea0eeed13
js: 4.01kb increase (1.41kb/gzip)

**Review by notlee — APPROVED** [review]
🎉

**Pull request merged**
