### PR TITLE
Generate fallback guid when window.crypto not defined

### PR DESCRIPTION
**Pull request by adgad**
/cc @markstephens @charypar @AlbertoElias 

Fixes https://github.com/Financial-Times/o-tracking/issues/66
(there might be a more efficient way of doing this than a try/finally)

### CODE REVIEW

**Comment by georgecrawford** [comment]
@adgad tweaked a bit - OK with this?

**Comment by adgad** [comment]
Typo in hasWindowCtypto - otherwise :+1:

**Comment by georgecrawford** [comment]
Damnation, thanks.

**Comment by markstephens** [comment]
Thanks for the catch guys!



--
Mark Stephens
BI Solutions Architect
Financial Times Ltd ft.com
Email: mark.stephens@ft.com
Int Ext: 4251
Tel: 020 7873 4251

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

On 1 September 2015 at 15:16, George Crawford <notifications@github.com>
wrote:

> Damnation, thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-tracking/pull/67#issuecomment-136735777>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Pull request merged**
