### PR TITLE
Change build URL

### PR DESCRIPTION
**Pull request by j-mes**
Migrating from Akamai to Fastly.

### CODE REVIEW

**Comment by onishiweb** [comment]
This looks ok but can you check out why the tests are failing? Shouldn't they be going to Circle anyway?

**Comment by j-mes** [comment]
I did wonder why it failed, and why it was using Travis. I think it might be worth bringing up with someone that maintains o-ads? Maybe @markstephens (judging by the most recent commits to this module) could offer some insight on this?

**Comment by markstephens** [comment]
I'd need to lean on @AlbertoElias and/or @wheresrhys - I don't know

**Comment by AlbertoElias** [comment]
@j-mes do you want to give it a go moving this to circle and see if you can fix ci?

**Comment by j-mes** [comment]
Definitely. I'll look into this.

**Comment by j-mes** [comment]
This works fine with being changed to Circle CI from Travis CI. Needs a 2nd pair of eyes before this can be merged. @AlbertoElias ?

**Comment by AlbertoElias** [comment]
lgtm

**Pull request merged**
