### PR TITLE
Info for dev

### PR DESCRIPTION
**Pull request by markstephens**
- Update readme
- Fix logging

### CODE REVIEW

**Comment by AlbertoElias** [comment]
Oh, my bad here. Can you pudate the .travis.yml file and change `obt` to `origami-build-tools` please?

**Comment by markstephens** [comment]
@AlbertoElias it's better! But unfortunately still not working
https://travis-ci.org/Financial-Times/o-tracking/builds/64899938#L119

**Comment by AlbertoElias** [comment]
Try changing the node.js version to `"0.12.2"`

**Comment by markstephens** [comment]
@AlbertoElias yep, it passed. Will merge now..

**Pull request merged**
