### PR TITLE
Remove version from `package.json`. Update version in `main.js`

### PR DESCRIPTION
**Pull request by notlee**
Thie commit removes the version number from `package.json`
to align with the Origami spec (it's currently outdated anyway).

The version number is also set in `main.js` is incorrect. This commit
updates it for the new major. It's likely to fall out of date again.
We should consider removing it in a future version of o-tracking but
first need to understand if/how it's used.

https://github.com/Financial-Times/o-tracking/issues/195

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-tracking bundle size difference from 1.7.3 to 3cfea4ef6f675e7909040f4d9fb884da1415a433
No significant bundle size differences found.

**Comment by JakeChampion** [comment]
The version is sent with each request sent to spoor -- https://github.com/Financial-Times/o-tracking/blob/21e43d1fcb8d003c7e7e91ae9f396dc2e79764c6/src/javascript/core/send.js#L51

**Comment by notlee** [comment]
> The version is sent with each request sent to spoor --
> 
> https://github.com/Financial-Times/o-tracking/blob/21e43d1fcb8d003c7e7e91ae9f396dc2e79764c6/src/javascript/core/send.js#L51

But I wonder if it's used 🤔 It can't hold up the major cascade, so let's leave for a future o-tracking focused work

**Comment by origamiserviceuser** [comment]
o-tracking bundle size difference from 1.7.3 to 4dfc5bbef4c918881d8b3069709c4f230ccc7f9d
js: 3.9kb increase (0.73kb/gzip)

**Pull request merged**
