### PR TITLE
Link tracking

### PR DESCRIPTION
**Pull request by markstephens**
Match spec @ https://drive.google.com/open?id=18G4oEkfdMbG719YmMnIHeOcD8hVHLk4q9Dr-7pazxRk

### CODE REVIEW

**Comment by georgecrawford** [comment]
Position and siblings?

**Comment by markstephens** [comment]
Yeah, haven't got there yet, and Not sure I can work them out generically, probably the product has to tell me. They can be passed in already..

**Comment by commuterjoy** [comment]
Next uses camel case FWIW.

Is this attached to all events on the page? Or should it / can it be initialised explicitly.

**Comment by commuterjoy** [comment]
> and not sure I can work them out generically,

I don't think you can, but if the products decorates the DOM with position/sibling attributes then `o-tracking` can capture the values, Eg.

https://github.com/Financial-Times/n-ui/blob/master/tracking/ft/events/cta.js#L58

**Comment by markstephens** [comment]
>Is this attached to all events on the page? Or should it / can it be initialised explicitly.

You can tell it to listen on all A tags (other elements too), or call it explicitly yourself (e.g. custom event or call the function directly)

> if the products decorates the DOM with position/sibling attributes then o-tracking can capture the values

Yes, that's true, but what about links that we haven't set those attributes for?

**Comment by commuterjoy** [comment]
> Yes, that's true, but what about links that we haven't set those attributes for?

They just don't get captured. It's only an optional field.

**Comment by markstephens** [comment]
Yes, ok, same as `data-trackable`

**Comment by commuterjoy** [comment]
> Yes, ok, same as data-trackable

yup!

**Pull request merged**
