### PR TITLE
Tp/removeid

### PR DESCRIPTION
**Pull request by tom-parker**

### CODE REVIEW

**Comment by tavvy** [comment]
👍 🚢

**Comment by notlee** [comment]
@tom-parker is this still something you would like merged?

**Comment by tom-parker** [comment]
@notlee ah, yes I think so. Sorry, this one slipped my mind

**Comment by notlee** [comment]
Cool. Out of interest why remove the id?

**Comment by notlee** [comment]
@tom-parker Ah, second question (bare with me I'm new to o-tracking), does this not constitute a breaking change if someone is relying on the id for their tracking?

**Comment by tom-parker** [comment]
I don't think this is a breaking change, from memory it was actually a bug. On click events I think `context.id` actually contains the id of the event. In circumstances where there was a id attribute on some clickable element, we'd end up overriding the id of the click event with the id attribute of the element if that makes sense.

**Comment by notlee** [comment]
👍  :shipit:

**Comment by markstephens** [comment]
`context.id` should be a unique ID for the event.
If you want to store another ID somewhere, it needs to go somewhere else.
Looking at Tom's changes, I think the code looks good to reflect this.

**Comment by JakeChampion** [comment]
After merging in the latest changes from master, it looks like this work was done in a different pull-request.

**Pull request closed without merging**
